server.port=9090

#configuring consumer
spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=mostafa
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#For string deserialization.
#spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#For json deserialization.
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

#configuring producer
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#For string serialization.
#spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
#For json serialization.
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

#spring.kafka.topic.name=StringData
spring.kafka.topic-json.name=JsonData